---
- name: Fetch user and group details for given user across cluster
  hosts: all
  become: yes
  gather_facts: no

  vars:
    username: ""

  tasks:
    - name: Fail if username is not provided
      fail:
        msg: "You must provide a username to fetch info. Example: -e 'username=johndoe'"
      when: username == ""

    - name: Check if user exists
      command: id {{ username }}
      register: user_info
      ignore_errors: yes

    - name: Fetch passwd entry if user exists
      command: getent passwd {{ username }}
      register: passwd_info
      when: user_info.rc == 0
      ignore_errors: yes

    - name: Fetch group entry if user exists
      command: getent group {{ username }}
      register: group_info
      when: user_info.rc == 0
      ignore_errors: yes

    - name: Show user info if found
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "User info: {{ user_info.stdout }}"
          - "Passwd entry: {{ passwd_info.stdout | default('N/A') }}"
          - "Group entry: {{ group_info.stdout | default('N/A') }}"
      when: user_info.rc == 0

    - name: Show user not found
      debug:
        msg: "Host: {{ inventory_hostname }} - User '{{ username }}' not found"
      when: user_info.rc != 0
